""" Constants definitions. """
import os

PYDBCLI_DATABASE_URL_ENV = 'PYDBCLI_DATABASE_URL'
PYDBCLI_DATABASE_URL = os.environ.get(PYDBCLI_DATABASE_URL_ENV)

# TODO: Check if these defaults are correct for parse (zero padded pref)
PYDBCLI_DATETIME_FORMAT_ENV = 'PYDBCLI_DATETIME_FORMAT'
PYDBCLI_DATETIME_FORMAT_DEFAULT = '%Y%m%d-%H%M%S'
PYDBCLI_DATETIME_FORMAT = os.environ.get(PYDBCLI_DATETIME_FORMAT_ENV,
                                         PYDBCLI_DATETIME_FORMAT_DEFAULT)

PYDBCLI_DATE_FORMAT_ENV = 'PYDBCLI_DATE_FORMAT'
PYDBCLI_DATE_FORMAT_DEFAULT = '%Y%m%d'
PYDBCLI_DATE_FORMAT = os.environ.get(PYDBCLI_DATE_FORMAT_ENV,
                                     PYDBCLI_DATE_FORMAT_DEFAULT)

PYDBCLI_TIME_FORMAT_ENV = 'PYDBCLI_TIME_FORMAT'
PYDBCLI_TIME_FORMAT_DEFAULT = '%H%M%S'
PYDBCLI_TIME_FORMAT = os.environ.get(PYDBCLI_TIME_FORMAT_ENV,
                                     PYDBCLI_TIME_FORMAT_DEFAULT)
